# Generated by Django 5.1.3 on 2025-02-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_subject_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Video',
            new_name='video',
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
